// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgcrhoauipofprxflzry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnY3Job2F1aXBvZnByeGZsenJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzk0MjIsImV4cCI6MjA2MDk1NTQyMn0.Ifiom-_4qxHcc5ozRKIxalH3RtIVr5R67N4mLuW33f4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);